// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6t7dKGQmxlKalfeGq7Zdzafafeu6ctDc',
    appId: '1:403723916584:web:0218548917552d3d78ac1d',
    messagingSenderId: '403723916584',
    projectId: 'mainproject-e4b9d',
    authDomain: 'mainproject-e4b9d.firebaseapp.com',
    storageBucket: 'mainproject-e4b9d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwZHA6L1G1K7_-m84_L7x65tBtZkOLOY4',
    appId: '1:403723916584:android:283b942cdd92290b78ac1d',
    messagingSenderId: '403723916584',
    projectId: 'mainproject-e4b9d',
    storageBucket: 'mainproject-e4b9d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPr_Cl7OBstvtdh8w8iOxYpbep5dAsLPY',
    appId: '1:403723916584:ios:da557365073e924b78ac1d',
    messagingSenderId: '403723916584',
    projectId: 'mainproject-e4b9d',
    storageBucket: 'mainproject-e4b9d.firebasestorage.app',
    iosBundleId: 'com.example.authFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPr_Cl7OBstvtdh8w8iOxYpbep5dAsLPY',
    appId: '1:403723916584:ios:da557365073e924b78ac1d',
    messagingSenderId: '403723916584',
    projectId: 'mainproject-e4b9d',
    storageBucket: 'mainproject-e4b9d.firebasestorage.app',
    iosBundleId: 'com.example.authFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6t7dKGQmxlKalfeGq7Zdzafafeu6ctDc',
    appId: '1:403723916584:web:a5c6fc900f98161178ac1d',
    messagingSenderId: '403723916584',
    projectId: 'mainproject-e4b9d',
    authDomain: 'mainproject-e4b9d.firebaseapp.com',
    storageBucket: 'mainproject-e4b9d.firebasestorage.app',
  );
}
